grep -i -r . -e mscorlib.dll.so
grep -i -r . -e mscorlib.dll.so
grep -i -r . -e TimeDateCalculator.gtk.exe.so
grep -i -r . -e TimeDateCalculator.gtk.exe.so
grep -i -r . -e TimeDateCalculator.gtk.exe.so
grep -i -r . -e TimeDateCalculator.gtk.exe.so
grep -i -r . -e TimeDateCalculatorDll.dll.so
grep -i -r . -e TimeDateCalculatorDll.dll.so
grep -i -r . -e Xamarin.Forms.Core.dll.so
grep -i -r . -e Xamarin.Forms.Core.dll.so
grep -i -r . -e netstandard.dll.so
grep -i -r . -e netstandard.dll.so
grep -i -r . -e System.dll.so
grep -i -r . -e System.dll.so
grep -i -r . -e Xamarin.Forms.Platform.GTK.dll.so
grep -i -r . -e Xamarin.Forms.Platform.GTK.dll.so
grep -i -r . -e gtk-sharp.dll.so
grep -i -r . -e gtk-sharp.dll.so
grep -i -r . -e glib-sharp.dll.so
grep -i -r . -e glib-sharp.dll.so
grep -i -r . -e atk-sharp.dll.so
grep -i -r . -e atk-sharp.dll.so
grep -i -r . -e gdk-sharp.dll.so
grep -i -r . -e gdk-sharp.dll.so
grep -i -r . -e libgtk-x11-2.0.so.0
grep -i -r . -e libgtk-x11-2.0.so.0.so
grep -i -r . -e libgtk-x11-2.0.so.0.so
grep -i -r . -e libgtk-x11-2.0.so.0
grep -i -r . -e libgtk-x11-2.0.so.0.so
grep -i -r . -e libgtk-x11-2.0.so.0.so
grep -i -r . -e user32.dll
grep -i -r . -e libuser32.dll.so
grep -i -r . -e libuser32.dll.so
grep -i -r . -e user32.dll
grep -i -r . -e libuser32.dll.so
grep -i -r . -e libuser32.dll.so
grep -i -r . -e user32.dll
grep -i -r . -e libuser32.dll.so
grep -i -r . -e libuser32.dll.so
grep -i -r . -e user32.dll
grep -i -r . -e user32
grep -i -r . -e libuser32.so
grep -i -r . -e libuser32.so
grep -i -r . -e user32
grep -i -r . -e libuser32.so
grep -i -r . -e libuser32.so
grep -i -r . -e user32
grep -i -r . -e libuser32.so
grep -i -r . -e libuser32.so
grep -i -r . -e user32
grep -i -r . -e libuser32.dll
grep -i -r . -e libuser32.dll.so
grep -i -r . -e libuser32.dll.so
grep -i -r . -e libuser32.dll
grep -i -r . -e libuser32.dll.so
grep -i -r . -e libuser32.dll.so
grep -i -r . -e libuser32.dll
grep -i -r . -e libuser32.dll.so
grep -i -r . -e libuser32.dll.so
grep -i -r . -e libuser32.dll
grep -i -r . -e libMonoSupportW.so
grep -i -r . -e libMonoSupportW.so
grep -i -r . -e libMonoSupportW.so
grep -i -r . -e libglib-2.0.so.0
grep -i -r . -e libglib-2.0.so.0.so
grep -i -r . -e libglib-2.0.so.0.so
grep -i -r . -e libglib-2.0.so.0
grep -i -r . -e libglib-2.0.so.0.so
grep -i -r . -e libglib-2.0.so.0.so
grep -i -r . -e System.Core.dll.so
grep -i -r . -e System.Core.dll.so
grep -i -r . -e netstandard.dll.so
grep -i -r . -e netstandard.dll.so
grep -i -r . -e Xamarin.Forms.Xaml.dll.so
grep -i -r . -e Xamarin.Forms.Xaml.dll.so
grep -i -r . -e netstandard.dll.so
grep -i -r . -e netstandard.dll.so
grep -i -r . -e Xamarin.Forms.Platform.dll.so
grep -i -r . -e Xamarin.Forms.Platform.dll.so
grep -i -r . -e netstandard.dll.so
grep -i -r . -e netstandard.dll.so
grep -i -r . -e System.Xml.dll.so
grep -i -r . -e System.Xml.dll.so
grep -i -r . -e System.Drawing.dll.so
grep -i -r . -e System.Drawing.dll.so
grep -i -r . -e libgobject-2.0.so.0
grep -i -r . -e libgobject-2.0.so.0.so
grep -i -r . -e libgobject-2.0.so.0.so
grep -i -r . -e libgobject-2.0.so.0
grep -i -r . -e libgobject-2.0.so.0.so
grep -i -r . -e libgobject-2.0.so.0.so
grep -i -r . -e Mono.Cairo.dll.so
grep -i -r . -e Mono.Cairo.dll.so
