grep -i -r -e 'mscorlib.dll.so' -f .
grep -i -r -e 'mscorlib.dll.so' -f .
grep -i -r -e 'TimeDateCalculator.gtk.exe.so' -f .
grep -i -r -e 'TimeDateCalculator.gtk.exe.so' -f .
grep -i -r -e 'TimeDateCalculator.gtk.exe.so' -f .
grep -i -r -e 'TimeDateCalculator.gtk.exe.so' -f .
grep -i -r -e 'TimeDateCalculatorDll.dll.so' -f .
grep -i -r -e 'TimeDateCalculatorDll.dll.so' -f .
grep -i -r -e 'Xamarin.Forms.Core.dll.so' -f .
grep -i -r -e 'Xamarin.Forms.Core.dll.so' -f .
grep -i -r -e 'netstandard.dll.so' -f .
grep -i -r -e 'netstandard.dll.so' -f .
grep -i -r -e 'System.dll.so' -f .
grep -i -r -e 'System.dll.so' -f .
grep -i -r -e 'Xamarin.Forms.Platform.GTK.dll.so' -f .
grep -i -r -e 'Xamarin.Forms.Platform.GTK.dll.so' -f .
grep -i -r -e 'gtk-sharp.dll.so' -f .
grep -i -r -e 'gtk-sharp.dll.so' -f .
grep -i -r -e 'glib-sharp.dll.so' -f .
grep -i -r -e 'glib-sharp.dll.so' -f .
grep -i -r -e 'atk-sharp.dll.so' -f .
grep -i -r -e 'atk-sharp.dll.so' -f .
grep -i -r -e 'gdk-sharp.dll.so' -f .
grep -i -r -e 'gdk-sharp.dll.so' -f .
grep -i -r -e 'libgtk-x11-2.0.so.0' -f .
grep -i -r -e 'libgtk-x11-2.0.so.0.so' -f .
grep -i -r -e 'libgtk-x11-2.0.so.0.so' -f .
grep -i -r -e 'libgtk-x11-2.0.so.0' -f .
grep -i -r -e 'libgtk-x11-2.0.so.0.so' -f .
grep -i -r -e 'libgtk-x11-2.0.so.0.so' -f .
grep -i -r -e 'user32.dll' -f .
grep -i -r -e 'libuser32.dll.so' -f .
grep -i -r -e 'libuser32.dll.so' -f .
grep -i -r -e 'user32.dll' -f .
grep -i -r -e 'libuser32.dll.so' -f .
grep -i -r -e 'libuser32.dll.so' -f .
grep -i -r -e 'user32.dll' -f .
grep -i -r -e 'libuser32.dll.so' -f .
grep -i -r -e 'libuser32.dll.so' -f .
grep -i -r -e 'user32.dll' -f .
grep -i -r -e 'user32' -f .
grep -i -r -e 'libuser32.so' -f .
grep -i -r -e 'libuser32.so' -f .
grep -i -r -e 'user32' -f .
grep -i -r -e 'libuser32.so' -f .
grep -i -r -e 'libuser32.so' -f .
grep -i -r -e 'user32' -f .
grep -i -r -e 'libuser32.so' -f .
grep -i -r -e 'libuser32.so' -f .
grep -i -r -e 'user32' -f .
grep -i -r -e 'libuser32.dll' -f .
grep -i -r -e 'libuser32.dll.so' -f .
grep -i -r -e 'libuser32.dll.so' -f .
grep -i -r -e 'libuser32.dll' -f .
grep -i -r -e 'libuser32.dll.so' -f .
grep -i -r -e 'libuser32.dll.so' -f .
grep -i -r -e 'libuser32.dll' -f .
grep -i -r -e 'libuser32.dll.so' -f .
grep -i -r -e 'libuser32.dll.so' -f .
grep -i -r -e 'libuser32.dll' -f .
grep -i -r -e 'libMonoSupportW.so' -f .
grep -i -r -e 'libMonoSupportW.so' -f .
grep -i -r -e 'libMonoSupportW.so' -f .
grep -i -r -e 'libglib-2.0.so.0' -f .
grep -i -r -e 'libglib-2.0.so.0.so' -f .
grep -i -r -e 'libglib-2.0.so.0.so' -f .
grep -i -r -e 'libglib-2.0.so.0' -f .
grep -i -r -e 'libglib-2.0.so.0.so' -f .
grep -i -r -e 'libglib-2.0.so.0.so' -f .
grep -i -r -e 'System.Core.dll.so' -f .
grep -i -r -e 'System.Core.dll.so' -f .
grep -i -r -e 'netstandard.dll.so' -f .
grep -i -r -e 'netstandard.dll.so' -f .
grep -i -r -e 'Xamarin.Forms.Xaml.dll.so' -f .
grep -i -r -e 'Xamarin.Forms.Xaml.dll.so' -f .
grep -i -r -e 'netstandard.dll.so' -f .
grep -i -r -e 'netstandard.dll.so' -f .
grep -i -r -e 'Xamarin.Forms.Platform.dll.so' -f .
grep -i -r -e 'Xamarin.Forms.Platform.dll.so' -f .
grep -i -r -e 'netstandard.dll.so' -f .
grep -i -r -e 'netstandard.dll.so' -f .
grep -i -r -e 'System.Xml.dll.so' -f .
grep -i -r -e 'System.Xml.dll.so' -f .
grep -i -r -e 'System.Drawing.dll.so' -f .
grep -i -r -e 'System.Drawing.dll.so' -f .
grep -i -r -e 'libgobject-2.0.so.0' -f .
grep -i -r -e 'libgobject-2.0.so.0.so' -f .
grep -i -r -e 'libgobject-2.0.so.0.so' -f .
grep -i -r -e 'libgobject-2.0.so.0' -f .
grep -i -r -e 'libgobject-2.0.so.0.so' -f .
grep -i -r -e 'libgobject-2.0.so.0.so' -f .
grep -i -r -e 'Mono.Cairo.dll.so' -f .
grep -i -r -e 'Mono.Cairo.dll.so' -f .
