find . -path ./mnt -prune -o -name '*mscorlib.dll.so*' -print
find . -path ./mnt -prune -o -name '*mscorlib.dll.so*' -print
find . -path ./mnt -prune -o -name '*TimeDateCalculator.gtk.exe.so*' -print
find . -path ./mnt -prune -o -name '*TimeDateCalculator.gtk.exe.so*' -print
find . -path ./mnt -prune -o -name '*TimeDateCalculator.gtk.exe.so*' -print
find . -path ./mnt -prune -o -name '*TimeDateCalculator.gtk.exe.so*' -print
find . -path ./mnt -prune -o -name '*TimeDateCalculatorDll.dll.so*' -print
find . -path ./mnt -prune -o -name '*TimeDateCalculatorDll.dll.so*' -print
find . -path ./mnt -prune -o -name '*Xamarin.Forms.Core.dll.so*' -print
find . -path ./mnt -prune -o -name '*Xamarin.Forms.Core.dll.so*' -print
find . -path ./mnt -prune -o -name '*netstandard.dll.so*' -print
find . -path ./mnt -prune -o -name '*netstandard.dll.so*' -print
find . -path ./mnt -prune -o -name '*System.dll.so*' -print
find . -path ./mnt -prune -o -name '*System.dll.so*' -print
find . -path ./mnt -prune -o -name '*Xamarin.Forms.Platform.GTK.dll.so*' -print
find . -path ./mnt -prune -o -name '*Xamarin.Forms.Platform.GTK.dll.so*' -print
find . -path ./mnt -prune -o -name '*gtk-sharp.dll.so*' -print
find . -path ./mnt -prune -o -name '*gtk-sharp.dll.so*' -print
find . -path ./mnt -prune -o -name '*glib-sharp.dll.so*' -print
find . -path ./mnt -prune -o -name '*glib-sharp.dll.so*' -print
find . -path ./mnt -prune -o -name '*atk-sharp.dll.so*' -print
find . -path ./mnt -prune -o -name '*atk-sharp.dll.so*' -print
find . -path ./mnt -prune -o -name '*gdk-sharp.dll.so*' -print
find . -path ./mnt -prune -o -name '*gdk-sharp.dll.so*' -print
find . -path ./mnt -prune -o -name '*libgtk-x11-2.0.so.0*' -print
find . -path ./mnt -prune -o -name '*libgtk-x11-2.0.so.0.so*' -print
find . -path ./mnt -prune -o -name '*libgtk-x11-2.0.so.0.so*' -print
find . -path ./mnt -prune -o -name '*libgtk-x11-2.0.so.0*' -print
find . -path ./mnt -prune -o -name '*libgtk-x11-2.0.so.0.so*' -print
find . -path ./mnt -prune -o -name '*libgtk-x11-2.0.so.0.so*' -print
find . -path ./mnt -prune -o -name '*user32.dll*' -print
find . -path ./mnt -prune -o -name '*libuser32.dll.so*' -print
find . -path ./mnt -prune -o -name '*libuser32.dll.so*' -print
find . -path ./mnt -prune -o -name '*user32.dll*' -print
find . -path ./mnt -prune -o -name '*libuser32.dll.so*' -print
find . -path ./mnt -prune -o -name '*libuser32.dll.so*' -print
find . -path ./mnt -prune -o -name '*user32.dll*' -print
find . -path ./mnt -prune -o -name '*libuser32.dll.so*' -print
find . -path ./mnt -prune -o -name '*libuser32.dll.so*' -print
find . -path ./mnt -prune -o -name '*user32.dll*' -print
find . -path ./mnt -prune -o -name '*user32*' -print
find . -path ./mnt -prune -o -name '*libuser32.so*' -print
find . -path ./mnt -prune -o -name '*libuser32.so*' -print
find . -path ./mnt -prune -o -name '*user32*' -print
find . -path ./mnt -prune -o -name '*libuser32.so*' -print
find . -path ./mnt -prune -o -name '*libuser32.so*' -print
find . -path ./mnt -prune -o -name '*user32*' -print
find . -path ./mnt -prune -o -name '*libuser32.so*' -print
find . -path ./mnt -prune -o -name '*libuser32.so*' -print
find . -path ./mnt -prune -o -name '*user32*' -print
find . -path ./mnt -prune -o -name '*libuser32.dll*' -print
find . -path ./mnt -prune -o -name '*libuser32.dll.so*' -print
find . -path ./mnt -prune -o -name '*libuser32.dll.so*' -print
find . -path ./mnt -prune -o -name '*libuser32.dll*' -print
find . -path ./mnt -prune -o -name '*libuser32.dll.so*' -print
find . -path ./mnt -prune -o -name '*libuser32.dll.so*' -print
find . -path ./mnt -prune -o -name '*libuser32.dll*' -print
find . -path ./mnt -prune -o -name '*libuser32.dll.so*' -print
find . -path ./mnt -prune -o -name '*libuser32.dll.so*' -print
find . -path ./mnt -prune -o -name '*libuser32.dll*' -print
find . -path ./mnt -prune -o -name '*libMonoSupportW.so*' -print
find . -path ./mnt -prune -o -name '*libMonoSupportW.so*' -print
find . -path ./mnt -prune -o -name '*libMonoSupportW.so*' -print
find . -path ./mnt -prune -o -name '*libglib-2.0.so.0*' -print
find . -path ./mnt -prune -o -name '*libglib-2.0.so.0.so*' -print
find . -path ./mnt -prune -o -name '*libglib-2.0.so.0.so*' -print
find . -path ./mnt -prune -o -name '*libglib-2.0.so.0*' -print
find . -path ./mnt -prune -o -name '*libglib-2.0.so.0.so*' -print
find . -path ./mnt -prune -o -name '*libglib-2.0.so.0.so*' -print
find . -path ./mnt -prune -o -name '*System.Core.dll.so*' -print
find . -path ./mnt -prune -o -name '*System.Core.dll.so*' -print
find . -path ./mnt -prune -o -name '*netstandard.dll.so*' -print
find . -path ./mnt -prune -o -name '*netstandard.dll.so*' -print
find . -path ./mnt -prune -o -name '*Xamarin.Forms.Xaml.dll.so*' -print
find . -path ./mnt -prune -o -name '*Xamarin.Forms.Xaml.dll.so*' -print
find . -path ./mnt -prune -o -name '*netstandard.dll.so*' -print
find . -path ./mnt -prune -o -name '*netstandard.dll.so*' -print
find . -path ./mnt -prune -o -name '*Xamarin.Forms.Platform.dll.so*' -print
find . -path ./mnt -prune -o -name '*Xamarin.Forms.Platform.dll.so*' -print
find . -path ./mnt -prune -o -name '*netstandard.dll.so*' -print
find . -path ./mnt -prune -o -name '*netstandard.dll.so*' -print
find . -path ./mnt -prune -o -name '*System.Xml.dll.so*' -print
find . -path ./mnt -prune -o -name '*System.Xml.dll.so*' -print
find . -path ./mnt -prune -o -name '*System.Drawing.dll.so*' -print
find . -path ./mnt -prune -o -name '*System.Drawing.dll.so*' -print
find . -path ./mnt -prune -o -name '*libgobject-2.0.so.0*' -print
find . -path ./mnt -prune -o -name '*libgobject-2.0.so.0.so*' -print
find . -path ./mnt -prune -o -name '*libgobject-2.0.so.0.so*' -print
find . -path ./mnt -prune -o -name '*libgobject-2.0.so.0*' -print
find . -path ./mnt -prune -o -name '*libgobject-2.0.so.0.so*' -print
find . -path ./mnt -prune -o -name '*libgobject-2.0.so.0.so*' -print
find . -path ./mnt -prune -o -name '*Mono.Cairo.dll.so*' -print
find . -path ./mnt -prune -o -name '*Mono.Cairo.dll.so*' -print
